export default [{key:"tempMax", name:"Max Temp", selected: true},
{key:"tempAvg", name: "Avg temp", selected: true},
{key:"tempMin", name: "Min temp", selected: true},
{key:"precip", name: "Precipitation", selected: true},
{key:"snowfall", name: "Snowfall", selected: true},
{key:"windSpdMax", name:"Max Wind Spd", selected: true},
{key:"windSpdAvg", name: "Avg Wind Spd", selected: true},
{key:"windSpdMin", name: "Min Wind Spd", selected: true},
{key:"dewPtMax", name:"Max Dew Pt.", selected: true},
{key:"dewPtAvg", name: "Avg Dew Pt.", selected: true},
{key:"dewPtMin", name: "Min Dew Pt.", selected: true},
{key:"feelsLikeMax", name:"Max \"Feels Like\"", selected: true},
{key:"feelsLikeAvg", name: "Avg \"Feels Like\"", selected: true},
{key:"feelsLikeMin", name: "Min \"Feels Like\"", selected: true}]
